#!/bin/sh /etc/rc.common
START=99
EXTRA_COMMANDS="single"

start () {
   /usr/bin/multiwan agent &
}

stop () {
  sh /usr/bin/multiwan stop
}

restart () {
  stop
  start
}

reload () {
  stop
  start
}
  
